openapi: "3.0.0"
info:
  version: 1.0.0
  title: Sharity Docs
servers:
  - url: http://localhost:5000
paths:
  /user:
    $ref: "./userapi.yml#user"
  /user/{userId}:
    $ref: "./userapi.yml#user~1{userId}"
  /ngo:
    $ref: "./ngoapi.yml#ngo"
  /ngo/{ngoId}:
    $ref: "./ngoapi.yml#ngo~1{ngoId}"
  /auth/{user_id}:
    $ref: "./authapi.yml#auth~1{user_id}"

components:
  securitySchemes:
    bearerAuth:            
      type: http
      in: header
      scheme: bearer
      bearerFormat: JWT

    ApiKeyAuth:        
      type: apiKey
      in: header       
      name: token
  $ref: "./schemas.yml"
